### ISSUE TITLE
Thoughts on finding entity to update

### ISSUE THREAD

**Issue by markosski** [mattia-battiston/clean-architecture-example#2]
I noticed your models/entities do not cary ID generated by DB. It does makes sense to me that we don't want to expose this as different data providers may handle record IDs differently. I'm thinking about the best way to handle case of User entity where somewhere on the outside request comes in to update information of a User. Email address could be used in such case or perhaps UUID. Thoughts?

**Comment by mattia-battiston** [comment]
@martez81 you're right, I don't expose the database id as it only makes sense for the db and not for the other data providers. Ideally I'd use a natural identifier for the entities.
The example you mention makes perfect sense: if someone wants to update info of a user, I would look up that user in the database by something unique about them (e.g. by username, or by email address).

Having said that, I can mention another technique that I tried in the past but ended up not liking. 
Say that we have an entity called User. In the database module you extend it and have UserInDb, which holds its databaseId. Now the other modules can still pass around an object of type User which knows nothing about databaseId, and only in the database module you cast it back to UserInDb.
As I said, this works, but I didn't like it very much as it relies on the casting of User to UserInDb, which might not be safe if the User object was created by a module other than the database. If possible, I'd keep looking up the user by a natural key.

**Comment by markosski** [comment]
Thanks, this is helpful.
