### ISSUE TITLE
[QUESTION] How to avoid duplicate interactor

### ISSUE THREAD

**Issue by hukadev** [mattia-battiston/clean-architecture-example#4]
Hello,

What if I create a new use case, like getSomething, and use the same DoesExchangeExist class.
Should I use this class or create new class for new use case?
Thanks in advance!

Best regards,
Huka

**Comment by mattia-battiston** [comment]
Hi Hung

The easiest thing you can do is extract the DoesPostEsisted class to a common package and reuse it from both use cases. I don't see anything wrong with it, as it sounds like it's part of your business logic. 

I hope this answer your questions
Cheers

**Comment by hukadev** [comment]
Hi @mattia-battiston 

Thank you so much for your comment.
Do you mean I should create another common use case and use it in other use cases?

Example:
- Put common interactor in common package:
com.example.core.usecase.common.DoesPostEsisted.java

- Used in:
com.example.core.usecase.getcapacity.GetCapacityForExchangeUseCase.java

- And
com.example.core.usecase.getSomething.GetSomethingForSomethingUseCase.java


Edit:
I think it should be called Boundaries, not Interactors, is it right?

Thanks,
Hung.

**Comment by mattia-battiston** [comment]
yes, that's what I mean. There's nothing wrong in extracting duplicate code, as long as you still respected the fact that in core we only want business logic.

Not sure what you mean by boundaries vs interactors though?

Mattia

**Comment by hukadev** [comment]
I'm confusing, Boundaries are interface, Interactors are Usecases.
Maybe DoesPostEsisted.java is Boundary and used in others Usecases.
I will search Google for more details.

Thank you for supporting, I really appreciate it.

Have a good day!
Hung
