### ISSUE TITLE
Q: what layer should Gateway interface belong to?

### ISSUE THREAD

**Issue by 4ntoine** [mattia-battiston/clean-architecture-example#6]
Should it be "domain" or "use case"?
I can see reasons for both answers.

Any thoughts about it?

**Comment by mattia-battiston** [comment]
In my example, both domain and use cases are in the module that I call core, so it probably doesn't make much difference.
But in answer to your question (hoping that I'm not misunderstanding it), I think the gateway interface should live next to the use case that is going to use it.

Mattia
